plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "3.0.7"
  "vue-jest@*":
    dependencies:
      "@vue/compiler-sfc": "latest"
      "source-map": "^0.6.0"
  "jest-playwright-preset@*":
    dependencies:
      "playwright": "^1.9.1"
      "playwright-chromium": "^1.9.1"
